
'use client';

import React from 'react';
import { useExamModuleGenerator } from '@/hooks/use-ielts-generator';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Separator } from '@/components/ui/separator';

export default function IeltsGeneratorPage() {
  const { loading, error, result, generate } = useExamModuleGenerator();

  return (
    <div className="container mx-auto max-w-5xl space-y-8 p-4">
      <Card className="bg-card/50">
        <CardHeader>
          <CardTitle>IELTS Module Generator</CardTitle>
          <CardDescription>
            Select the exam variant to generate a complete vocabulary module using AI.
            Please note that generation may take a minute or two.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4 mb-4">
            <Button onClick={() => generate('Academic')} disabled={loading}>
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Generate Academic Module
            </Button>
            <Button onClick={() => generate('General Training')} disabled={loading}>
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Generate General Training Module
            </Button>
          </div>

          {loading && (
            <div className="flex items-center gap-2 text-muted-foreground">
              <Loader2 className="h-5 w-5 animate-spin" />
              <span>Generating modules... This can take up to a minute. Please wait.</span>
            </div>
          )}

          {error && <p className="text-destructive">{error}</p>}

        </CardContent>
      </Card>
      
      {result && (
        <Card>
            <CardHeader>
                <CardTitle>Generated IELTS Module</CardTitle>
                <CardDescription>Here is the content generated by the AI.</CardDescription>
            </CardHeader>
            <Separator />
            <CardContent className="pt-6">
                 <div className="prose prose-sm dark:prose-invert max-w-none">
                    <ReactMarkdown>{result}</ReactMarkdown>
                </div>
            </CardContent>
        </Card>
      )}
    </div>
  );
}
