
import type { NeetModule } from '@/lib/types';

export const electrostaticsModule: NeetModule = {
    id: 'neet-physics-electrostatics',
    title: 'Physics - Electrostatics (நிலைமின்னியல்)',
    chapter: 'Electrostatics',
    subject: 'Physics',
    learningObjectives: [
        "Understand and apply Coulomb's Law to calculate the force between point charges.",
        "Define and visualize the electric field and electric potential for various charge distributions.",
        "Apply Gauss's law to calculate the electric field for symmetric charge distributions.",
        "Understand the concept of electric potential energy and its relation to work done.",
        "Analyze the behavior of conductors and dielectrics in an external electric field.",
        "Define capacitance and analyze series and parallel combinations of capacitors.",
        "Calculate the energy stored in a capacitor."
    ],
    prerequisites: [
        "Newton's Laws of Motion",
        "Work, Energy, and Power",
        "Basic concepts of vectors and calculus"
    ],
    conceptOverview: "Electrostatics is the study of electric charges at rest. It's the starting point for understanding all of electricity and magnetism. This chapter introduces the fundamental concepts of electric charge, the force between charges (Coulomb's Law), and the way charges create electric fields and potentials in the space around them. We will explore Gauss's law as a powerful tool for calculating electric fields and then introduce the capacitor, a fundamental component for storing electrical energy. The principles learned here are foundational to nearly all modern technology.",
    tamilConnection: "மின்னல் ஒரு பிரம்மாண்டமான நிலைமின்னியல் நிகழ்வு. பண்டைத் தமிழர்கள் இடி, மின்னல் போன்ற இயற்கை நிகழ்வுகளைக் கண்டு வியந்தனர். இந்த அத்தியாயம், அந்த நிகழ்வுகளுக்குப் பின்னால் உள்ள அடிப்படை அறிவியல் கொள்கையான மின்னூட்டங்கள் மற்றும் விசைகளை விளக்குகிறது.",
    culturalContext: "Think of a silk saree sticking to your body after being folded and stored for a long time. This is due to static electricity generated by the friction between the silk layers. Electrostatics explains these everyday phenomena of attraction and repulsion that we often observe.",
    syllabusMapping: [
         {
            topic: 'Electric Charges and Fields, Electrostatic Potential and Capacitance',
            tnBoardChapter: '12th Std Physics - Vol 1, Chapter 1: Electrostatics',
            ncertReference: 'Class 12 Physics - Part 1, Chapters 1 & 2',
            notes: 'A very high-weightage unit in NEET. Problems on electric field/potential due to dipoles, Gauss\'s law applications, and capacitor circuits (series/parallel, dielectrics) are extremely common.',
            mappingDescription: '12th Std Physics - Vol 1, Chapter 1 maps to NEET Physics Unit 11'
        }
    ],
    conceptNotes: [
        {
            english: `### 1. Electric Charge and Coulomb's Law (மின்னூட்டம் மற்றும் கூலூம் விதி)
*   **Electric Charge (மின்னூட்டம்):** The fundamental property of matter that causes it to experience a force when placed in an electromagnetic field. It is quantized ($q=ne$) and conserved.
*   **Coulomb's Law (கூலூம் விதி):** The force of attraction or repulsion between two stationary point charges is directly proportional to the product of the magnitudes of the charges and inversely proportional to the square of the distance between them.
$$
\\vec{F} = \\frac{1}{4\\pi\\epsilon_0} \\frac{q_1 q_2}{r^2} \\hat{r}
$$
    *   $\epsilon_0$ is the permittivity of free space.
    *   The force is attractive for unlike charges and repulsive for like charges.`
        },
        {
            english: `### 2. Electric Field (மின்புலம்)
The electric field ($\\vec{E}$) at a point is the force experienced by a unit positive test charge placed at that point. It is a vector field.
$$
\\vec{E} = \\frac{\\vec{F}}{q_0}
$$
*   **Electric Field due to a Point Charge q:** $\\vec{E} = \\frac{1}{4\\pi\\epsilon_0} \\frac{q}{r^2} \\hat{r}$
*   **Electric Field Lines (மின்புலக் கோடுகள்):** Imaginary lines drawn in an electric field along which a positive test charge would move. They originate from positive charges and terminate on negative charges. The tangent to a field line at any point gives the direction of the electric field at that point.`
        },
        {
            english: `### 3. Electric Dipole (மின் இருமுனை)
An electric dipole consists of two equal and opposite charges separated by a small distance (2a).
*   **Dipole Moment (இருமுனைத் திருப்புத்திறன், $\\vec{p}$):** A vector quantity with magnitude $p = q(2a)$, directed from the negative to the positive charge.
*   **Electric Field on Axial Line:** $E_{axial} = \\frac{1}{4\\pi\\epsilon_0} \\frac{2p}{r^3}$ (for r >> a)
*   **Electric Field on Equatorial Line:** $E_{equatorial} = \\frac{1}{4\\pi\\epsilon_0} \\frac{p}{r^3}$ (for r >> a)
*   **Torque on a Dipole in a Uniform Electric Field:** $\\vec{\\tau} = \\vec{p} \\times \\vec{E}$
*   **Potential Energy of a Dipole:** $U = -\\vec{p} \\cdot \\vec{E}$`
        },
        {
            english: `### 4. Gauss's Law (காஸ் விதி)
Gauss's law provides a powerful way to calculate the electric field for symmetric charge distributions.
*   **Electric Flux (மின்பாயம், $\\Phi_E$):** The number of electric field lines passing normally through a surface. $\\Phi_E = \\int \\vec{E} \\cdot d\\vec{A}$.
*   **Gauss's Law Statement:** The total electric flux through any closed surface (Gaussian surface) is equal to $1/\\epsilon_0$ times the net charge enclosed by the surface.
$$
\\oint \\vec{E} \\cdot d\\vec{A} = \\frac{q_{enclosed}}{\\epsilon_0}
$$`
        },
        {
            english: `### 5. Electrostatic Potential and Capacitance (நிலைமின்னழுத்தம் மற்றும் மின்தேக்குத்திறன்)
*   **Electric Potential (V) (மின்னழுத்தம்):** Work done per unit charge in bringing a charge from infinity to a point in the electric field. $V = W/q$. It is a scalar quantity.
*   **Potential due to a Point Charge:** $V = \\frac{1}{4\\pi\\epsilon_0} \\frac{q}{r}$
*   **Relation between E and V:** The electric field is the negative gradient of the potential. $E = -dV/dr$.
*   **Capacitance (C) (மின்தேக்குத்திறன்):** The ability of a conductor to store charge. It is the ratio of charge stored to the potential difference. $C = Q/V$. Unit: Farad (F).
*   **Parallel Plate Capacitor:** $C = \\frac{\\epsilon_0 A}{d}$ (in vacuum).
*   **Effect of Dielectric:** When a dielectric material of dielectric constant K is inserted, capacitance increases: $C' = KC$.
*   **Capacitors in Series:** $\\frac{1}{C_s} = \\frac{1}{C_1} + \\frac{1}{C_2} + ...$
*   **Capacitors in Parallel:** $C_p = C_1 + C_2 + ...$
*   **Energy Stored in a Capacitor:** $U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C} = \\frac{1}{2}QV`
        }
    ],
    workedExamples: [
        { title: "Coulomb's Law", difficulty: 'Easy', problem: "Two point charges of +2 μC and +6 μC repel each other with a force of 12 N. If each is given an additional charge of -4 μC, what will be the new force?", solutionSteps: [], neetHack: "" },
        { title: "Electric Field", difficulty: 'Medium', problem: "Three charges are placed at the vertices of an equilateral triangle of side 'a'. Find the electric field at the centroid.", solutionSteps: [], neetHack: "" },
        { title: "Gauss's Law", difficulty: 'Medium', problem: "A point charge of 10 μC is at the center of a cube of side 10 cm. What is the net electric flux through the cube?", solutionSteps: [], neetHack: "" },
        { title: "Capacitor Network", difficulty: 'Hard', problem: "Find the equivalent capacitance between points A and B in the given infinite ladder network of capacitors.", solutionSteps: [], neetHack: "" },
        { title: "Energy Stored in Capacitor", difficulty: 'Easy', problem: "A 20 μF capacitor is charged to a potential of 500 V and then disconnected from the battery. It is then connected to another uncharged 10 μF capacitor. Find the common potential and the loss of energy.", solutionSteps: [], neetHack: "" }
    ],
    mcqs: [
        { question: "The SI unit of electric flux is:", options: ["A. N C⁻¹ m²", "B. N C m⁻²", "C. V m", "D. N C⁻¹"], answer: "A. N C⁻¹ m²", explanation: "Electric flux Φ = E⋅A. Unit of E is N/C and unit of A is m². So, unit of flux is N m²/C.", neetFrequency: 3 },
        { question: "A hollow metal sphere of radius 10 cm is charged such that the potential on its surface is 80 V. The potential at the center of the sphere is:", options: ["A. 0 V", "B. 80 V", "C. 800 V", "D. 8 V"], answer: "B. 80 V", explanation: "The electric field inside a charged hollow sphere is zero. Therefore, the potential is constant inside the sphere and equal to the potential on the surface.", neetFrequency: 5 },
        { question: "Three capacitors each of capacity C are connected in series. Their equivalent capacity will be:", options: ["A. 3C", "B. C/3", "C. 3/C", "D. 1/3C"], answer: "B. C/3", explanation: "For series combination, 1/C_eq = 1/C₁ + 1/C₂ + 1/C₃ = 1/C + 1/C + 1/C = 3/C. So, C_eq = C/3.", neetFrequency: 4 },
        { question: "An electric dipole placed in a uniform electric field experiences:", options: ["A. A net force but no torque", "B. A torque but no net force", "C. Both a net force and a torque", "D. Neither a net force nor a torque"], answer: "B. A torque but no net force", explanation: "The forces on the two charges of the dipole are equal and opposite, so the net force is zero. However, these forces form a couple, resulting in a net torque.", neetFrequency: 4 },
        { question: "When a dielectric slab is introduced between the plates of a parallel plate capacitor, its capacitance:", options: ["A. Decreases", "B. Increases", "C. Remains unchanged", "D. May increase or decrease"], answer: "B. Increases", explanation: "The capacitance of a parallel plate capacitor with a dielectric of constant K is C' = KC₀, where C₀ is the capacitance in vacuum. Since K > 1, the capacitance increases.", neetFrequency: 5 },
        { question: "Electric field lines provide information about:", options: ["A. Field strength", "B. Direction of force", "C. Nature of charge", "D. All of the above"], answer: "D. All of the above", explanation: "Density of lines gives strength, tangent gives direction, and origin/termination gives nature of charge.", neetFrequency: 2 },
        { question: "The work done in moving a charge of 1 C from a point at potential 10 V to another point at potential 15 V is:", options: ["A. 5 J", "B. 1 J", "C. 150 J", "D. 0.5 J"], answer: "A. 5 J", explanation: "Work done W = q * ΔV = 1 C * (15 V - 10 V) = 5 J.", neetFrequency: 3 },
        { question: "The capacitance of a parallel plate capacitor does not depend on:", options: ["A. Area of the plates", "B. Medium between the plates", "C. Distance between the plates", "D. Metal of the plates"], answer: "D. Metal of the plates", explanation: "Capacitance C = εA/d. It depends on the area (A), distance (d), and the permittivity of the medium (ε), but not on the material of the plates.", neetFrequency: 3 },
        { question: "Two point charges +3μC and +8μC repel each other with a force of 40 N. If a charge of -5μC is added to each of them, then the force between them will become:", options: ["A. -10 N", "B. +10 N", "C. +20 N", "D. -20 N"], answer: "A. -10 N", explanation: "Initial force F = k(q₁q₂)/r² = k(3*8)/r² = 24k/r² = 40N. New charges are q₁' = 3-5 = -2μC and q₂' = 8-5 = +3μC. New force F' = k(-2*3)/r² = -6k/r². F'/F = (-6k/r²)/(24k/r²) = -1/4. F' = -F/4 = -40/4 = -10 N.", neetFrequency: 4 },
        { question: "An equipotential surface is one where:", options: ["A. Electric field is uniform", "B. Potential is zero", "C. Potential is constant", "D. Electric field is zero"], answer: "C. Potential is constant", explanation: "By definition, all points on an equipotential surface have the same electric potential.", neetFrequency: 2 },
        { question: "A charge Q is enclosed by a Gaussian spherical surface of radius R. If the radius is doubled, then the outward electric flux will:", options: ["A. Be doubled", "B. Be halved", "C. Remain the same", "D. Become four times"], answer: "C. Remain the same", explanation: "According to Gauss's law, the total electric flux depends only on the charge enclosed (Φ = Q_enclosed/ε₀) and is independent of the size or shape of the Gaussian surface.", neetFrequency: 5 },
        { question: "A parallel plate capacitor is charged and then the battery is disconnected. If the plates are moved further apart, the:", options: ["A. Charge increases", "B. Potential difference increases", "C. Capacitance increases", "D. Energy stored decreases"], answer: "B. Potential difference increases", explanation: "Since the battery is disconnected, the charge Q remains constant. Moving plates apart decreases capacitance (C=εA/d). From Q=CV, if Q is constant and C decreases, the potential difference V must increase.", neetFrequency: 4 },
        { question: "What is the angle between the electric field and an equipotential surface?", options: ["A. 90° always", "B. 0° always", "C. Between 0° and 90°", "D. 180° always"], answer: "A. 90° always", explanation: "The electric field is always perpendicular to the equipotential surface at every point.", neetFrequency: 3 },
        { question: "The energy stored per unit volume in an electric field E is:", options: ["A. (1/2)ε₀E", "B. ε₀E²", "C. (1/2)ε₀E²", "D. (1/2)E²/ε₀"], answer: "C. (1/2)ε₀E²", explanation: "This is the formula for energy density in an electric field.", neetFrequency: 2 },
        { question: "The dimensional formula of electric potential is:", options: ["A. [ML²T⁻³A⁻¹]", "B. [MLT⁻³A⁻¹]", "C. [ML²T⁻²A⁻¹]", "D. [MLT⁻²A⁻²]"], answer: "A. [ML²T⁻³A⁻¹]", explanation: "Potential V = W/q = Work/(Current*Time). Dimensions are [ML²T⁻²]/([A][T]) = [ML²T⁻³A⁻¹].", neetFrequency: 3 },
        { question: "When a soap bubble is charged:", options: ["A. It contracts", "B. It expands", "C. It bursts", "D. Its size remains the same"], answer: "B. It expands", explanation: "The charges on the surface repel each other, creating an outward pressure which causes the bubble to expand.", neetFrequency: 2 },
        { question: "The electric field lines for a positive point charge are:", options: ["A. Radially outwards", "B. Radially inwards", "C. Parallel straight lines", "D. Circular"], answer: "A. Radially outwards", explanation: "Electric field lines originate from positive charges and extend outwards to infinity.", neetFrequency: 1 },
        { question: "Two capacitors of 2μF and 4μF are connected in parallel. A 300V potential difference is applied across the combination. The charge on the 2μF capacitor is:", options: ["A. 600 μC", "B. 1200 μC", "C. 1800 μC", "D. 900 μC"], answer: "A. 600 μC", explanation: "In a parallel combination, the voltage across each capacitor is the same (300V). Charge Q = CV = (2μF)(300V) = 600 μC.", neetFrequency: 4 },
        { question: "Dielectric constant of a metal is:", options: ["A. 0", "B. 1", "C. -1", "D. Infinity"], answer: "D. Infinity", explanation: "The electric field inside a conductor is zero. Since E = E_ext/K, for E to be zero, the dielectric constant K must be infinite.", neetFrequency: 3 },
        { question: "What is the electric field inside a uniformly charged non-conducting sphere at its center?", options: ["A. Infinity", "B. Zero", "C. Depends on radius", "D. Depends on charge"], answer: "B. Zero", explanation: "Due to symmetry, the electric field contributions from all parts of the sphere cancel out at the center.", neetFrequency: 2 },
        { question: "The work done in rotating an electric dipole in an electric field from a position of stable equilibrium to unstable equilibrium is:", options: ["A. pE", "B. 2pE", "C. -pE", "D. 0"], answer: "B. 2pE", explanation: "Work W = ΔU = U_final - U_initial. Stable equilibrium is at θ=0 (U=-pE). Unstable equilibrium is at θ=180° (U=+pE). W = (+pE) - (-pE) = 2pE.", neetFrequency: 4 },
        { question: "A parallel plate capacitor is charged by a battery. After charging, the battery is disconnected and a dielectric slab is inserted. The potential difference between the plates will:", options: ["A. Increase", "B. Decrease", "C. Remain constant", "D. Become zero"], answer: "B. Decrease", explanation: "Charge Q remains constant. Inserting a dielectric increases capacitance C. From V=Q/C, if Q is constant and C increases, V must decrease.", neetFrequency: 5 },
        { question: "Electric lines of force about a negative point charge are:", options: ["A. Circular, clockwise", "B. Circular, anticlockwise", "C. Radially inwards", "D. Radially outwards"], answer: "C. Radially inwards", explanation: "Electric field lines terminate on negative charges, so they are directed radially inwards.", neetFrequency: 1 },
        { question: "The force between two charges is 120 N. If the distance between the charges is doubled, the force will be:", options: ["A. 60 N", "B. 30 N", "C. 40 N", "D. 15 N"], answer: "B. 30 N", explanation: "Force is inversely proportional to the square of the distance (F ∝ 1/r²). If distance is doubled, force becomes 1/4th. F' = 120 / 4 = 30 N.", neetFrequency: 3 },
        { question: "Coulomb's law is valid for:", options: ["A. Point charges", "B. Distributed charges", "C. Both point and distributed charges", "D. Only charges in motion"], answer: "A. Point charges", explanation: "Coulomb's law in its basic form is strictly valid for stationary point charges.", neetFrequency: 2 }
    ],
    assertionReasons: [
        { assertion: "The electric field inside a charged conductor is always zero.", reason: "In the static situation, charges reside on the surface of the conductor, and the net electric field inside is zero.", answer: "A", explanation: "Assertion is true. Reason is also true and is the correct explanation. If there were a field, charges would move, which contradicts the static situation.", neetFrequency: 4 },
        { assertion: "Work done in moving a charge between any two points on an equipotential surface is zero.", reason: "The potential difference between any two points on an equipotential surface is zero.", answer: "A", explanation: "Assertion is true. Reason is true and is the correct explanation. Work done W = q * ΔV. Since ΔV=0 on an equipotential surface, W=0.", neetFrequency: 3 },
        { assertion: "When a dielectric is introduced between the plates of a capacitor, the capacitance increases.", reason: "The dielectric material reduces the effective electric field between the plates.", answer: "A", explanation: "Assertion is true. Reason is also true and is the correct explanation. The reduced electric field leads to a reduced potential difference for the same charge (V=Ed), and since C=Q/V, capacitance increases.", neetFrequency: 5 },
        { assertion: "Electric lines of force never cross each other.", reason: "The tangent to an electric field line at any point gives the direction of the electric field at that point.", answer: "A", explanation: "Assertion is true. Reason is also true and is the correct explanation. If two lines crossed, it would mean that there are two different directions of the electric field at the same point, which is physically impossible.", neetFrequency: 3 },
        { assertion: "A capacitor is a device that stores energy in the form of an electric field.", reason: "The energy stored in a capacitor is given by U = (1/2)CV².", answer: "B", explanation: "Both assertion and reason are true statements. However, the formula for energy does not explain *why* the energy is stored in the electric field. The explanation lies in the work done to separate the charges and create the field.", neetFrequency: 2 }
    ],
    matchTheColumns: [
        { column1: ["(a) Electric Field", "(b) Electric Potential", "(c) Electric Dipole Moment", "(d) Electric Flux"], column2: ["(p) Scalar, Vm", "(q) Vector, NC⁻¹", "(r) Vector, Cm", "(s) Scalar, NC⁻¹m²"], answer: "a-q, b-p, c-r, d-s", explanation: "Matching quantities with their nature (scalar/vector) and SI units." },
        { column1: ["(a) Parallel Plate Capacitor", "(b) Capacitors in Series", "(c) Capacitors in Parallel", "(d) Energy in Capacitor"], column2: ["(p) 1/C_eq = Σ(1/C_i)", "(q) C_eq = ΣC_i", "(r) (1/2)CV²", "(s) ε₀A/d"], answer: "a-s, b-p, c-q, d-r", explanation: "Matching concepts with their corresponding formulas." },
        { column1: ["(a) Inside a hollow charged sphere", "(b) On the surface of a charged conductor", "(c) Inside a charged non-conductor", "(d) Due to a dipole on equatorial line"], column2: ["(p) Field is non-zero", "(q) Field is zero", "(r) Field is perpendicular to surface", "(s) Field is parallel to dipole axis"], answer: "a-q, b-r, c-p, d-s", explanation: "Matching locations with properties of the electric field." },
        { column1: ["(a) Conductor", "(b) Insulator", "(c) Semiconductor", "(d) Superconductor"], column2: ["(p) Very large energy gap", "(q) Zero resistance", "(r) No energy gap", "(s) Small energy gap"], answer: "a-r, b-p, c-s, d-q", explanation: "Matching material types with their energy band gap properties." },
        { column1: ["(a) Quantization of charge", "(b) Conservation of charge", "(c) Coulomb's Law", "(d) Gauss's Law"], column2: ["(p) Force between charges", "(q) Total flux is Q/ε₀", "(r) q = ne", "(s) Total charge of an isolated system is constant"], answer: "a-r, b-s, c-p, d-q", explanation: "Matching fundamental laws and principles with their statements." }
    ],
    keyFormulasAndDiagrams: {},
    keyTakeaways: [],
    mnemonics: [],
    neetTips: [],
    validationReport: []
}
