
import type { NeetModule } from '@/lib/types';

export const electromagneticWaves: NeetModule = {
  id: 'physics-electromagnetic-waves',
  title: 'Electromagnetic Waves',
  chapter: 'Electromagnetic Waves',
  subject: 'Physics',
  conceptNotes: `
### 1. Displacement Current (இடப்பெயர்ச்சி மின்னோட்டம்)
*   Introduced by Maxwell to modify Ampere's circuital law.
*   A current that comes into play whenever the electric field and hence the electric flux is changing with time. I_d = ε₀(dΦ_E/dt).
*   It ensures the consistency of Ampere's law.

### 2. Maxwell's Equations (மாக்ஸ்வெல் சமன்பாடுகள்)
*   A set of four fundamental equations that form the foundation of classical electromagnetism. They describe how electric and magnetic fields are generated and altered by each other and by charges and currents.

### 3. Electromagnetic (EM) Waves (மின்காந்த அலைகள்)
*   Generated by accelerating charges.
*   **Properties:**
    1.  They are transverse in nature, meaning the electric field (E), magnetic field (B), and the direction of propagation are all mutually perpendicular. (மின்புலம், காந்தப்புலம், மற்றும் அலை பரவும் திசை மூன்றும் ஒன்றுக்கொன்று செங்குத்தாக இருக்கும்).
    2.  They do not require a medium for propagation and can travel in a vacuum.
    3.  They travel in vacuum with the speed of light, c = 1/√(μ₀ε₀) ≈ 3 x 10⁸ m/s.
    4.  The ratio of the magnitudes of the electric and magnetic fields is E/B = c.
    5.  They carry energy and momentum.

### 4. Electromagnetic Spectrum (மின்காந்த நிறமாலை)
*   The arrangement of EM waves according to their frequency or wavelength.
*   **Order of increasing wavelength (and decreasing frequency/energy):**
    Gamma rays (காமா கதிர்கள்) → X-rays (எக்ஸ்-கதிர்கள்) → Ultraviolet (புற ஊதா) → Visible light (கண்ணுறு ஒளி) → Infrared (அகச்சிவப்பு) → Microwaves (நுண்ணலைகள்) → Radio waves (ரேடியோ அலைகள்).
*   **Uses of different waves:**
    *   **Radio waves:** Communication systems (radio, TV).
    *   **Microwaves:** Radar, microwave ovens.
    *   **Infrared:** Remote controls, thermal imaging.
    *   **Visible light:** Vision, photography.
    *   **Ultraviolet:** Sterilization, detecting forged documents.
    *   **X-rays:** Medical imaging (radiography), studying crystal structures.
    *   **Gamma rays:** Radiotherapy for cancer treatment.
`,
  workedExamples: [
    {
        problem: "The magnetic field in a plane electromagnetic wave is given by B_y = (2 × 10⁻⁷) sin(0.5 × 10³x + 1.5 × 10¹¹t) T. What is the expression for the electric field?",
        solution: "The standard equation is B_y = B₀sin(kx + ωt). Comparing this, we get B₀ = 2 × 10⁻⁷ T. The magnitude of the electric field is E₀ = cB₀ = (3 × 10⁸ m/s) * (2 × 10⁻⁷ T) = 60 V/m. Since the magnetic field is along the y-axis and the wave propagates along the -x axis (from kx+ωt), the electric field must be along the z-axis to be perpendicular to both. The expression for the electric field is E_z = 60 sin(0.5 × 10³x + 1.5 × 10¹¹t) V/m."
    },
    {
        problem: "A plane electromagnetic wave of frequency 25 MHz travels in free space along the x-direction. At a particular point in space and time, the electric field is E = 6.3 j V/m. What is the magnetic field B at this point?",
        solution: "The magnitude of the magnetic field is given by B = E/c. B = (6.3 V/m) / (3 × 10⁸ m/s) = 2.1 × 10⁻⁸ T. The direction of the magnetic field must be perpendicular to both the direction of propagation (x-axis) and the electric field (y-axis). According to the right-hand rule (E × B must be in the direction of propagation), if E is along +y and propagation is along +x, then B must be along the +z direction. So, B = 2.1 × 10⁻⁸ k T."
    },
    {
        problem: "Identify the part of the electromagnetic spectrum which is suitable for radar systems used in aircraft navigation.",
        solution: "The part of the electromagnetic spectrum suitable for radar systems is **microwaves**. Microwaves have wavelengths that are short enough to provide good resolution for detecting objects like aircraft, and they can penetrate haze, light rain, snow, clouds, and smoke."
    }
  ],
  mcqs: [],
  assertionReasons: [],
  matchTheColumns: []
};
