
import type { NeetModule } from '@/lib/types';

export const electrostaticsModule: NeetModule = {
    id: 'neet-physics-electrostatics',
    title: 'Physics - Electrostatics (நிலைமின்னியல்)',
    chapter: 'Electrostatics',
    subject: 'Physics',
    learningObjectives: [
        "Understand and apply Coulomb's Law to calculate the force between point charges.",
        "Define and visualize the electric field and electric potential for various charge distributions.",
        "Apply Gauss's law to calculate the electric field for symmetric charge distributions.",
        "Understand the concept of electric potential energy and its relation to work done.",
        "Analyze the behavior of conductors and dielectrics in an external electric field.",
        "Define capacitance and analyze series and parallel combinations of capacitors.",
        "Calculate the energy stored in a capacitor."
    ],
    prerequisites: [
        "Newton's Laws of Motion",
        "Work, Energy, and Power",
        "Basic concepts of vectors and calculus"
    ],
    conceptOverview: "Electrostatics is the study of electric charges at rest. It's the starting point for understanding all of electricity and magnetism. This chapter introduces the fundamental concepts of electric charge, the force between charges (Coulomb's Law), and the way charges create electric fields and potentials in the space around them. We will explore Gauss's law as a powerful tool for calculating electric fields and then introduce the capacitor, a fundamental component for storing electrical energy. The principles learned here are foundational to nearly all modern technology.",
    tamilConnection: "மின்னல் ஒரு பிரம்மாண்டமான நிலைமின்னியல் நிகழ்வு. பண்டைத் தமிழர்கள் இடி, மின்னல் போன்ற இயற்கை நிகழ்வுகளைக் கண்டு வியந்தனர். இந்த அத்தியாயம், அந்த நிகழ்வுகளுக்குப் பின்னால் உள்ள அடிப்படை அறிவியல் கொள்கையான மின்னூட்டங்கள் மற்றும் விசைகளை விளக்குகிறது.",
    culturalContext: "Think of a silk saree sticking to your body after being folded and stored for a long time. This is due to static electricity generated by the friction between the silk layers. Electrostatics explains these everyday phenomena of attraction and repulsion that we often observe.",
    syllabusMapping: [
         {
            topic: 'Electric Charges and Fields, Electrostatic Potential and Capacitance',
            tnBoardChapter: '12th Std Physics - Vol 1, Chapter 1: Electrostatics',
            ncertReference: 'Class 12 Physics - Part 1, Chapters 1 & 2',
            notes: 'A very high-weightage unit in NEET. Problems on electric field/potential due to dipoles, Gauss\'s law applications, and capacitor circuits (series/parallel, dielectrics) are extremely common.',
            mappingDescription: '12th Std Physics - Vol 1, Chapter 1 maps to NEET Physics Unit 11'
        }
    ],
    conceptNotes: `### 1. Electric Charge and Coulomb's Law (மின்னூட்டம் மற்றும் கூலூம் விதி)
*   **Electric Charge (மின்னூட்டம்):** The fundamental property of matter that causes it to experience a force when placed in an electromagnetic field. It is quantized ($q=ne$) and conserved.
*   **Coulomb's Law (கூலூம் விதி):** The force of attraction or repulsion between two stationary point charges is directly proportional to the product of the magnitudes of the charges and inversely proportional to the square of the distance between them.
$$
\\vec{F} = \\frac{1}{4\\pi\\epsilon_0} \\frac{q_1 q_2}{r^2} \\hat{r}
$$
    *   $\epsilon_0$ is the permittivity of free space.
    *   The force is attractive for unlike charges and repulsive for like charges.

### 2. Electric Field (மின்புலம்)
The electric field ($\vec{E}$) at a point is the force experienced by a unit positive test charge placed at that point. It is a vector field.
$$
\\vec{E} = \\frac{\\vec{F}}{q_0}
$$
*   **Electric Field due to a Point Charge q:** $\\vec{E} = \\frac{1}{4\\pi\\epsilon_0} \\frac{q}{r^2} \\hat{r}$
*   **Electric Field Lines (மின்புலக் கோடுகள்):** Imaginary lines drawn in an electric field along which a positive test charge would move. They originate from positive charges and terminate on negative charges. The tangent to a field line at any point gives the direction of the electric field at that point.

### 3. Electric Dipole (மின் இருமுனை)
An electric dipole consists of two equal and opposite charges separated by a small distance (2a).
*   **Dipole Moment (இருமுனைத் திருப்புத்திறன், $\\vec{p}$):** A vector quantity with magnitude $p = q(2a)$, directed from the negative to the positive charge.
*   **Electric Field on Axial Line:** $E_{axial} = \\frac{1}{4\\pi\\epsilon_0} \\frac{2p}{r^3}$ (for r >> a)
*   **Electric Field on Equatorial Line:** $E_{equatorial} = \\frac{1}{4\\pi\\epsilon_0} \\frac{p}{r^3}$ (for r >> a)
*   **Torque on a Dipole in a Uniform Electric Field:** $\\vec{\\tau} = \\vec{p} \\times \\vec{E}$
*   **Potential Energy of a Dipole:** $U = -\\vec{p} \\cdot \\vec{E}$

### 4. Gauss's Law (காஸ் விதி)
Gauss's law provides a powerful way to calculate the electric field for symmetric charge distributions.
*   **Electric Flux (மின்பாயம், $\\Phi_E$):** The number of electric field lines passing normally through a surface. $\\Phi_E = \\int \\vec{E} \\cdot d\\vec{A}$.
*   **Gauss's Law Statement:** The total electric flux through any closed surface (Gaussian surface) is equal to $1/\\epsilon_0$ times the net charge enclosed by the surface.
$$
\\oint \\vec{E} \\cdot d\\vec{A} = \\frac{q_{enclosed}}{\\epsilon_0}
$$

### 5. Electrostatic Potential and Capacitance (நிலைமின்னழுத்தம் மற்றும் மின்தேக்குத்திறன்)
*   **Electric Potential (V) (மின்னழுத்தம்):** Work done per unit charge in bringing a charge from infinity to a point in the electric field. $V = W/q$. It is a scalar quantity.
*   **Potential due to a Point Charge:** $V = \\frac{1}{4\\pi\\epsilon_0} \\frac{q}{r}$
*   **Relation between E and V:** The electric field is the negative gradient of the potential. $E = -dV/dr$.
*   **Capacitance (C) (மின்தேக்குத்திறன்):** The ability of a conductor to store charge. It is the ratio of charge stored to the potential difference. $C = Q/V$. Unit: Farad (F).
*   **Parallel Plate Capacitor:** $C = \\frac{\\epsilon_0 A}{d}$ (in vacuum).
*   **Effect of Dielectric:** When a dielectric material of dielectric constant K is inserted, capacitance increases: $C' = KC$.
*   **Capacitors in Series:** $\\frac{1}{C_s} = \\frac{1}{C_1} + \\frac{1}{C_2} + ...$
*   **Capacitors in Parallel:** $C_p = C_1 + C_2 + ...$
*   **Energy Stored in a Capacitor:** $U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C} = \\frac{1}{2}QV$
`,
    workedExamples: [],
    mcqs: [],
    assertionReasons: [],
    matchTheColumns: []
};
